spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 61a13d555b948a5d5b45
            clientSecret: 8141571f6c57f7b9d394ce470b31bca8cb6dc3f6
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            clientId: 660614002563-utibos6jbgkdsm0jofhelr65up8jmmfc.apps.googleusercontent.com
            clientSecret: SS3hjc-XrOH8blJOCpevBrjH
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

